version: '2.0'

services:
  komed-app:
    image: borntraegermarc/komed-app
    container_name: komed-app
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - komed-mongo
    volumes:
      - .:/home/app
    environment:
      - APP_ENV=dev # dev / beta / production
      - KEY_LOCATION=./misc/ssl/localhost/server.key
      - CERT_LOCATION=./misc/ssl/localhost/server.crt
      - MONGO_HOST=komed-mongo
      - MONGO_DATABASE=komed-health
      - PORT=5000
      - SSL_PORT=5001

  komed-mongo:
    container_name: komed-mongo
    image: mongo:3.2.11
