FROM node:6.9.2

RUN apt-get update

RUN useradd --user-group --create-home --shell /bin/false app

ENV HOME=/home/app

COPY package.json $HOME/
RUN chown -R app:app $HOME/*

USER app
WORKDIR $HOME/

RUN npm install --production \
&&  npm dedupe \
&&  npm cache clean \
&&  rm -rf /tmp/npm*

USER root

COPY . $HOME/

RUN chown -R app:app $HOME/*
USER app

CMD [ "npm", "run", "build" ]

CMD [ "npm", "start" ]
